/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __RS_BS_ALL_TYPES_H__
#define __RS_BS_ALL_TYPES_H__

#include <rs_bs/types/type_definitions.h>
#include <rs_bs/types/beliefstate_types.h>


#endif /* __RS_BS_ALL_TYPES_H__ */
