/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __RS_BS_TYPE_DEFINITIONS_H__
#define __RS_BS_TYPE_DEFINITIONS_H__

#define RS_BS_BELIEFSTATE_BELIEFSTATEOBJECT "rs_bs.beliefstate.BeliefStateObject"

#endif /* __RS_BS_TYPE_DEFINITIONS_H__ */
